export enum Intent {
  // General
  GREETING = "GREETING",
  GOODBYE = "GOODBYE",
  HELP = "HELP",
  UNKNOWN = "UNKNOWN",

  // Commerce
  ORDER_PRODUCT = "ORDER_PRODUCT",
  CANCEL_ORDER = "CANCEL_ORDER",
  ORDER_STATUS = "ORDER_STATUS",

  // Appointment
  BOOK_APPOINTMENT = "BOOK_APPOINTMENT",
  RESCHEDULE_APPOINTMENT = "RESCHEDULE_APPOINTMENT",
  CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT",

  // Reservation
  RESERVE_TABLE = "RESERVE_TABLE",
  CANCEL_RESERVATION = "CANCEL_RESERVATION",

  // Support
  GENERAL_INQUIRY = "GENERAL_INQUIRY",
}
