services:
  # db:
  #   image: postgres:16-alpine
  #   container_name: sparq-db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: sparq
  #   volumes:
  #     - sparq-db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: sparq-redis
    ports:
      - "6379:6379"
    volumes:
      - sparq-redis:/data

  sparq-api:
    image: sparq-api:1.0
    container_name: sparq-api
    ports:
      - "4000:4000"
    env_file:
      - ./apps/api/.env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  sparq-worker: 
    image: sparq-worker:1.0
    container_name: sparq-worker
    env_file:
      - ./apps/worker/.env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  sparq-db:
  sparq-redis:
  