export enum ReservationStep {
  WAITING_PARTY_SIZE = "WAITING_PARTY_SIZE",

  WAITING_DATE = "WAITING_DATE",

  WAITING_TIME = "WAITING_TIME",

  WAITING_CUSTOMER_DETAILS = "WAITING_CUSTOMER_DETAILS",

  WAITING_CONFIRMATION = "WAITING_CONFIRMATION",

  COMPLETED = "COMPLETED",
}
