export enum OrderStep {
  SEARCHING_PRODUCT = "SEARCHING_PRODUCT",

  WAITING_PRODUCT_SELECTION = "WAITING_PRODUCT_SELECTION",

  WAITING_CUSTOMER_DETAILS = "WAITING_CUSTOMER_DETAILS",

  WAITING_ADDRESS_CONFIRMATION = "WAITING_ADDRESS_CONFIRMATION",

  WAITING_QUANTITY = "WAITING_QUANTITY",

  WAITING_ORDER_CONFIRMATION = "WAITING_ORDER_CONFIRMATION",

  COMPLETED = "COMPLETED",
}
