export enum AppointmentStep {
  WAITING_SERVICE_SELECTION = "WAITING_SERVICE_SELECTION",

  WAITING_STAFF_SELECTION = "WAITING_STAFF_SELECTION",

  WAITING_LOCATION_CHOICE = "WAITING_LOCATION_CHOICE",

  WAITING_DATE = "WAITING_DATE",

  WAITING_TIME = "WAITING_TIME",

  WAITING_VISIT_ADDRESS = "WAITING_VISIT_ADDRESS",

  WAITING_CUSTOMER_DETAILS = "WAITING_CUSTOMER_DETAILS",

  WAITING_CONFIRMATION = "WAITING_CONFIRMATION",

  COMPLETED = "COMPLETED",
}
