export enum AppointmentStep {
  WAITING_SERVICE_SELECTION = "WAITING_SERVICE_SELECTION",

  WAITING_DATE = "WAITING_DATE",

  WAITING_TIME = "WAITING_TIME",

  WAITING_CUSTOMER_DETAILS = "WAITING_CUSTOMER_DETAILS",

  WAITING_CONFIRMATION = "WAITING_CONFIRMATION",

  COMPLETED = "COMPLETED",
}
